name: "SwiftLocation CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

concurrency:
  group: ci
  cancel-in-progress: true
  
jobs:
  ios-latest:
    name: Unit Tests (iOS 17.5, Xcode 15.4)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-xcode@v3
        with:
            xcode-version: '15.4'
      - name: Run Tests
        run: |
          Scripts/test.sh -s "SwiftLocation" -d "platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro"
 # macos-latest:
 #   name: Unit Tests (macOS, Xcode 14.3.1)
 #   runs-on: macOS-13
 #   env:
 #     DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
 #   steps:
 #     - uses: actions/checkout@v2
 #     - name: Run Tests
 #       run: Scripts/test.sh -d "platform=macOS"
  tvos-latest:
    name: Unit Tests (tvOS 17.5, Xcode 15.4)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-xcode@v3
        with:
            xcode-version: '15.4'
      - name: Run Tests
        run: |
          Scripts/test.sh -s "SwiftLocation" -d "platform=tvOS Simulator,OS=17.5,name=Apple TV 4K (3rd generation)"
